# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_sample_lscnn.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='training_sample_lscnn.proto',
  package='',
  serialized_pb='\n\x1btraining_sample_lscnn.proto\"\xd3\x02\n\x15training_sample_lscnn\x12\t\n\x01x\x18\x01 \x01(\x0c\x12\x0f\n\x07x_shape\x18\x02 \x03(\x05\x12\r\n\x05label\x18\x03 \x01(\x0c\x12\x13\n\x0blabel_shape\x18\x04 \x03(\x05\x12\x11\n\tdisk_data\x18\x07 \x01(\x0c\x12\x17\n\x0f\x64isk_data_shape\x18\x08 \x03(\x05\x12\x14\n\x0c\x64isk_indices\x18\t \x01(\x0c\x12\x1a\n\x12\x64isk_indices_shape\x18\n \x03(\x05\x12\x13\n\x0b\x64isk_indptr\x18\x0b \x01(\x0c\x12\x19\n\x11\x64isk_indptr_shape\x18\x0c \x03(\x05\x12\x13\n\x0blayer_begin\x18\r \x01(\x0c\x12\x19\n\x11layer_begin_shape\x18\x0e \x03(\x05\x12\x11\n\tlayer_end\x18\x0f \x01(\x0c\x12\x17\n\x0flayer_end_shape\x18\x10 \x03(\x05\x12\x10\n\x08\x66ilename\x18\x11 \x01(\x0c')




_TRAINING_SAMPLE_LSCNN = _descriptor.Descriptor(
  name='training_sample_lscnn',
  full_name='training_sample_lscnn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='training_sample_lscnn.x', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_shape', full_name='training_sample_lscnn.x_shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='training_sample_lscnn.label', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label_shape', full_name='training_sample_lscnn.label_shape', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_data', full_name='training_sample_lscnn.disk_data', index=4,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_data_shape', full_name='training_sample_lscnn.disk_data_shape', index=5,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_indices', full_name='training_sample_lscnn.disk_indices', index=6,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_indices_shape', full_name='training_sample_lscnn.disk_indices_shape', index=7,
      number=10, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_indptr', full_name='training_sample_lscnn.disk_indptr', index=8,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_indptr_shape', full_name='training_sample_lscnn.disk_indptr_shape', index=9,
      number=12, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layer_begin', full_name='training_sample_lscnn.layer_begin', index=10,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layer_begin_shape', full_name='training_sample_lscnn.layer_begin_shape', index=11,
      number=14, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layer_end', full_name='training_sample_lscnn.layer_end', index=12,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layer_end_shape', full_name='training_sample_lscnn.layer_end_shape', index=13,
      number=16, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='training_sample_lscnn.filename', index=14,
      number=17, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=371,
)

DESCRIPTOR.message_types_by_name['training_sample_lscnn'] = _TRAINING_SAMPLE_LSCNN

class training_sample_lscnn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRAINING_SAMPLE_LSCNN

  # @@protoc_insertion_point(class_scope:training_sample_lscnn)


# @@protoc_insertion_point(module_scope)
